---
- name: install PIP3
  yum: 
    name: "python3-pip"
    update_cache: yes
    state: present

- name: Pip install PyMySQL
  pip:
    name: PyMySQL
    state: present

- name: Install
  yum: 
    name: "{{ item }}"
    state: present
  loop:
    - mariadb-server

- name: Start mariadb
  systemd:
      name: mariadb
      state: started
      enabled: yes

- name: Update MariaDB root password
  mysql_user: 
    name: root
    host: "{{ item }}"
    password: "{{root_password}}"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
