---
- name: Install & Config Mariadb
  hosts: mariadb
  become: yes
  gather_facts: False
  vars_files: 
    - vars.yaml

  tasks:
  - name: Prepare
    community.general.apk: 
      name: "py3-pip"
      update_cache: yes
      no_cache: yes
      state: present

  - name: Prepare
    pip:
      name: PyMySQL
      state: present

  - name: Install
    apk: 
      name: "{{ item }}"
      state: present
    loop:
      - mariadb
      - mariadb-client

  - name: Setup mariadb
    command: /etc/init.d/mariadb setup
    ignore_errors: yes
  
  - name: Open external connections
    command: sed -i "s|.*bind-address\s*=.*|bind-address=0.0.0.0|g" /etc/my.cnf.d/mariadb-server.cnf

  - name: Open external connections
    command: sed -i 's/.*skip-networking/#skip-networking/' /etc/my.cnf.d/mariadb-server.cnf

  - name: Start mariadb
    sysvinit:
      name: mariadb
      state: started
      enabled: yes

  - name: Update MariaDB root password
    mysql_user: 
      login_user: root
      login_unix_socket: /var/run/mysqld/mysqld.sock
      login_password: "{{root_password}}"
      name: root
      host: localhost
      password: "{{root_password}}"

  - name: Create database user
    mysql_user:
      login_user: root
      login_unix_socket: /var/run/mysqld/mysqld.sock
      login_password: "{{root_password}}"
      name: "{{wotlk_db_user}}"
      host: "%"
      password: "{{wotlk_db_password}}"
      priv: '*.*:ALL'
      resource_limits:
        MAX_QUERIES_PER_HOUR: 0
        MAX_CONNECTIONS_PER_HOUR: 0
      state: present

  - name: Create databases
    community.mysql.mysql_db:
      login_user: root
      login_unix_socket: /var/run/mysqld/mysqld.sock
      login_password: "{{root_password}}"
      name: "{{ item }}"
      state: present
    loop:
        - auth
        - world
        - characters

  - name: Set mysql user privileges
    mysql_user:
      login_user: root
      login_unix_socket: /var/run/mysqld/mysqld.sock
      login_password: "{{root_password}}"
      name: "{{wotlk_db_user}}"
      host: "%"
      priv: "{{item}}.*:ALL"
      state: present
    loop:
      - auth
      - world
      - characters
